#!/usr/bin/env bash
# LAN Exam — Docker deploy on Linux (public Web/API on host port 8001).
# Run from repo root on the server: bash scripts/linux/deploy-docker.sh
set -eu
if (set -o pipefail) 2>/dev/null; then set -o pipefail; fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker not found. Install: https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 plugin not found."
  exit 1
fi

port_in_use() {
  local port="$1"
  if ss -tln 2>/dev/null | grep -qE ":${port}([[:space:]]|$)"; then
    return 0
  fi
  if command -v netstat >/dev/null 2>&1 && netstat -tln 2>/dev/null | grep -qE ":${port}([[:space:]]|$)"; then
    return 0
  fi
  return 1
}

WEB_HOST_PORT="${WEB_HOST_PORT:-8001}"
DB_HOST_PORT="${DB_HOST_PORT:-5434}"

if port_in_use "$WEB_HOST_PORT"; then
  echo "==> Port ${WEB_HOST_PORT} already in use (will recreate compose stack if it is this app)"
fi

echo "==> Host ports: WEB=${WEB_HOST_PORT} (app), DB=127.0.0.1:${DB_HOST_PORT} (postgres)"

if command -v ufw >/dev/null 2>&1 && sudo ufw status 2>/dev/null | grep -qi 'Status: active'; then
  echo "==> ufw: allow TCP ${WEB_HOST_PORT} (student exam access)"
  sudo ufw allow "${WEB_HOST_PORT}/tcp" || true
fi

ENV_FILE="${ROOT}/.env.deploy"
{
  echo "# Auto-generated by scripts/linux/deploy-docker.sh — do not commit"
  echo "WEB_HOST_PORT=${WEB_HOST_PORT}"
  echo "DB_HOST_PORT=${DB_HOST_PORT}"
  if [ -n "${SESSION_SECRET:-}" ]; then
    echo "SESSION_SECRET=${SESSION_SECRET}"
  fi
} >"$ENV_FILE"

if [ -z "${SESSION_SECRET:-}" ]; then
  if command -v openssl >/dev/null 2>&1; then
    export SESSION_SECRET="$(openssl rand -hex 24)"
  else
    export SESSION_SECRET="lan-exam-test-secret-$(date +%s)"
  fi
  echo "SESSION_SECRET=${SESSION_SECRET}" >>"$ENV_FILE"
  echo "==> Generated SESSION_SECRET (export SESSION_SECRET=... to set your own)"
fi

echo "==> Wrote ${ENV_FILE} (WEB_HOST_PORT=${WEB_HOST_PORT}, DB_HOST_PORT=${DB_HOST_PORT})"
rm -f "${ROOT}/docker-compose.override.yml"

COMPOSE_ENV="--env-file ${ENV_FILE}"
COMPOSE_FILES="-f docker-compose.yml -f docker-compose.host-app.yml"
if [ -f "${ROOT}/docker-compose.admin-remote.yml" ] && [ "${ADMIN_REMOTE:-false}" = "true" ]; then
  COMPOSE_FILES="${COMPOSE_FILES} -f docker-compose.admin-remote.yml"
  echo "==> Remote admin enabled (ADMIN_REMOTE=true + docker-compose.admin-remote.yml)"
fi

echo "==> docker compose up -d --build (host network app for SSH tunnel + admin API)"
docker compose $COMPOSE_ENV $COMPOSE_FILES up -d --build

echo ""
echo "==> Waiting for health..."
for i in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:${WEB_HOST_PORT}/health" | grep -q '"status":"ok"'; then
    echo "==> Health OK"
    break
  fi
  sleep 2
  if [ "$i" -eq 30 ]; then
    echo "==> Health check timed out. Logs:"
    docker compose $COMPOSE_ENV $COMPOSE_FILES logs --tail=50 app
    exit 1
  fi
done

PUBLIC_IP="$(curl -sf --max-time 3 ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
echo ""
echo "=============================================="
echo " Deployed LAN Exam (Docker)"
echo "----------------------------------------------"
echo " Web + API host port : ${WEB_HOST_PORT}"
echo " Postgres (localhost): 127.0.0.1:${DB_HOST_PORT}"
echo " Health              : http://127.0.0.1:${WEB_HOST_PORT}/health"
echo " Student (LAN)       : http://${PUBLIC_IP:-<SERVER_IP>}:${WEB_HOST_PORT}/exam/login"
echo ""
echo " Admin UI (loopback only):"
echo "   On your PC: ssh -L 5180:127.0.0.1:${WEB_HOST_PORT} ubuntu@<SERVER_IP>"
echo "   Browser   : http://127.0.0.1:5180/admin"
echo ""
echo " Open cloud security group / ufw for TCP ${WEB_HOST_PORT} if students connect remotely."
echo "=============================================="
docker compose $COMPOSE_ENV $COMPOSE_FILES ps
