-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Submission" ALTER COLUMN "totalScore" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Answer" ALTER COLUMN "pointsAwarded" SET DATA TYPE DOUBLE PRECISION;
